modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="togglecraft"
version="${mod_version}"
displayName="ToggleCraft"
description='''
A mod that adds a feature flag block to Minecraft.
Right-click to configure a LaunchDarkly feature flag key.
When the flag is true, the block emits a redstone signal of 16.
'''
authors="OurCraftOnCraft"

[[dependencies.togglecraft]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"

[[dependencies.togglecraft]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
